#!/usr/bin/env python3
"""Emit OEIS draft files for the 8 free-polyplet symmetry classes from the
validated table in results/symmetry_classes.txt (sym/symmetry_classes.py).

Each class is the count of free polyplets (A030222) whose symmetry group in D4 is
exactly the named subgroup; the 8 partition A030222 and refine the coarse
A030234 (bilateral)/A030235 split. Polyomino analogues exist (A006746 etc.);
polyplet analogues do not (novelty-checked, plain consecutive-term search clean).
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TABLE = os.path.join(ROOT, "results", "symmetry_classes.txt")
OUT = os.path.join(ROOT, "oeis")

# key, column, %N name, polyomino analogue
CLASSES = [
    ("asymmetric", 0,
     "Number of asymmetric free polyplets with n cells (king-move animals, A030222, with trivial symmetry group).",
     "A006749"),
    ("axial", 1,
     "Number of free polyplets (A030222) with n cells whose symmetry group has order 2, generated by a reflection in a grid-parallel axis.",
     "A006746"),
    ("diagonal", 2,
     "Number of free polyplets (A030222) with n cells whose symmetry group has order 2, generated by a reflection in a diagonal axis.",
     "A006748"),
    ("c2", 3,
     "Number of free polyplets (A030222) with n cells whose symmetry group is exactly the order-2 group generated by a 180-degree rotation.",
     "A006747"),
    ("c4", 4,
     "Number of free polyplets (A030222) with n cells whose symmetry group is exactly the cyclic group of order 4 generated by a 90-degree rotation (chiral; no reflection).",
     "A144553"),
    ("d2ortho", 5,
     "Number of free polyplets (A030222) with n cells whose symmetry group is the order-4 group generated by reflections in two perpendicular grid-parallel axes.",
     "A056877"),
    ("d2diag", 6,
     "Number of free polyplets (A030222) with n cells whose symmetry group is the order-4 group generated by reflections in the two diagonal axes.",
     "A056878"),
    ("d4", 7,
     "Number of free polyplets (A030222) with n cells having the full symmetry group of the square (order 8).",
     "A142886"),
]

rows = []
for line in open(TABLE):
    p = line.split()
    if len(p) >= 9 and p[0].isdigit():
        rows.append([int(x) for x in p[:9]])     # n + 8 class counts
rows.sort()

def offset2(vals):                                # index (1-based) of first |a|>1
    for i, v in enumerate(vals, 1):
        if abs(v) > 1:
            return i
    return 1

for key, col, name, analogue in CLASSES:
    data = [r[1 + col] for r in rows]             # n=1..19
    sibs = ", ".join(f"Axxxxx-{k}" for k, *_ in CLASSES if k != key)
    body = [
        f"%I Axxxxx-{key}",
        "%S Axxxxx-{0} {1}".format(key, ",".join(map(str, data))),
        f"%N Axxxxx-{key} {name}",
        f"%C Axxxxx-{key} A polyplet (polyking) is a set of unit cells joined through "
        f"shared edges or corners. The square symmetry group D4 partitions the free "
        f"polyplets A030222 into 8 classes by exact symmetry group; this is one of them. "
        f"The five reflection-containing classes (axial, diagonal, two-axis, two-diagonal, "
        f"full) sum to A030234 (bilaterally symmetric); the other three (asymmetric, "
        f"180-degree, 90-degree) sum to A030235. Polyplet analogue of {analogue} "
        f"(polyominoes). - _Jason H Parker_, 2026",
        f"%F Axxxxx-{key} Obtained via the table of marks of the square symmetry group "
        f"D4 from the counts of fixed polyplets (A006770) invariant under each subgroup. "
        f"The 8 symmetry classes partition A030222(n), and the five reflection classes "
        f"sum to A030234(n); both checked for all n <= 19.",
        f"%Y Axxxxx-{key} Cf. A030222 (free polyplets), A030234, A030235, A006770 "
        f"(fixed polyplets), {analogue} (polyomino analogue).",
        f"%K Axxxxx-{key} nonn,more",
        f"%O Axxxxx-{key} 1,{offset2(data)}",
        f"%A Axxxxx-{key} _Jason H Parker_, 2026",
    ]
    path = os.path.join(OUT, f"draft-sym-{key}.txt")
    with open(path, "w") as f:
        f.write("\n".join(body) + "\n")
    print(f"wrote {path}  ({len(data)} terms, offset 1,{offset2(data)})")
