#!/usr/bin/env python3
"""Extract Pin.lean input data: production diagonal polynomials + banked
onset points.

Reads diagCoeffTable from orchestrator/sweep.go (numerator coefficients,
descending powers of n, divided by kfact, times 3^(n-1-3k)) and the banked
triangle from results/triangle.txt, then for every k = 0..16:
  - cross-checks the production polynomial against EVERY banked in-onset
    point on diagonal k (fail-closed on any mismatch),
  - reports the onset points n = 2k+1..3k+1 with availability,
  - emits a machine-readable block for Lean transcription.

Output: polyplets/pin-data.md (committed reference for Pin.lean).
"""

import re
import sys
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SWEEP = ROOT / "orchestrator" / "sweep.go"
TRIANGLE = ROOT / "results" / "triangle.txt"
OUT = ROOT / "polyplets" / "pin-data.md"
NMAX = 36


def parse_table(src: str) -> dict[int, tuple[list[int], int]]:
    m = re.search(r"var diagCoeffTable = map\[int\]diagCoeffs\{(.*?)\n\}\n", src, re.S)
    if not m:
        sys.exit("diagCoeffTable not found in sweep.go")
    body = m.group(1)
    table: dict[int, tuple[list[int], int]] = {}
    for entry in re.finditer(r"\n\t(\d+): \{\[\]string\{(.*?)\}, (\d+)\}", body, re.S):
        k = int(entry.group(1))
        coeffs = [int(c) for c in re.findall(r'"(-?\d+)"', entry.group(2))]
        kfact = int(entry.group(3))
        if len(coeffs) != k + 1:
            sys.exit(f"k={k}: {len(coeffs)} coefficients, expected {k + 1}")
        table[k] = (coeffs, kfact)
    return table


def read_triangle() -> dict[tuple[int, int], int]:
    tri: dict[tuple[int, int], int] = {}
    for line in TRIANGLE.read_text().splitlines():
        if line.startswith("#") or not line.strip():
            continue
        n, h, t = line.split()
        tri[(int(n), int(h))] = int(t)
    return tri


def poly_value(coeffs: list[int], kfact: int, k: int, n: int) -> Fraction:
    num = 0
    for c in coeffs:
        num = num * n + c
    val = Fraction(num, kfact)
    e = n - 1 - 3 * k
    return val * Fraction(3) ** e


def main() -> None:
    table = parse_table(SWEEP.read_text())
    tri = read_triangle()
    lines = [
        "# Pin.lean input data (generated by scripts/extract_pin_data.py)",
        "",
        "Production polynomials from orchestrator/sweep.go diagCoeffTable",
        "(numerator coefficients DESCENDING in n, / k!, x 3^(n-1-3k)) and",
        f"banked onset points from results/triangle.txt (n <= {NMAX}).",
        "Every banked in-onset point re-verified against the polynomial at",
        "generation time; a mismatch aborts generation.",
        "",
    ]
    for k in range(0, 17):
        onset = 2 * k + 1
        pin_pts = list(range(onset, 3 * k + 2))
        banked = [n for n in range(onset, NMAX + 1) if (n, n - k) in tri]
        checked = 0
        for n in banked:
            want = tri[(n, n - k)]
            if k == 0:
                got = Fraction(3) ** (n - 1)
            else:
                coeffs, kfact = table[k]
                got = poly_value(coeffs, kfact, k, n)
            if got != want:
                sys.exit(f"MISMATCH k={k} n={n}: poly={got} banked={want}")
            checked += 1
        need = k + 1
        have = len(banked)
        lines.append(f"## k={k}")
        if k == 0:
            lines.append("P_0: T(n,n) = 3^(n-1)")
        else:
            coeffs, kfact = table[k]
            lines.append(f"numerator (desc n): {coeffs}")
            lines.append(f"kfact: {kfact}")
        lines.append(
            f"onset n>={onset}; banked in-onset points: {have} "
            f"(need {need} to pin) -> "
            + ("PINNABLE-FROM-BANKED" if have >= need else f"SHORTFALL {need - have}")
        )
        lines.append(f"verified against banked: {checked} points, all match")
        pin_rows = [f"T({n},{n - k}) = {tri[(n, n - k)]}" for n in pin_pts if (n, n - k) in tri]
        lines.append("pin points (first k+1 in-onset, banked subset):")
        lines.extend(f"  {r}" for r in pin_rows)
        missing = [n for n in pin_pts if (n, n - k) not in tri]
        if missing:
            lines.append(f"  MISSING (beyond banked range): n={missing}")
        lines.append("")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT}")
    print("all banked in-onset points verified against production polynomials")


if __name__ == "__main__":
    main()
