#!/usr/bin/env python3
"""Draw what Undertow changed, from banked numbers only.

Emits results/undertow-picture.md.  Every figure here is either read out of a
banked file or is a constant with its citation in the caption; nothing is
estimated in this script.  Run it after any change to the underlying data so
the picture cannot drift from the record.

Usage: python3 scripts/undertow_picture.py [> results/undertow-picture.md]
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# results/ns_a40/PROVENANCE.md, phases A/B/C
PHASES = [
    ("H <= 19", 6.3, 80, 69),
    ("H = 20", 9.6, 48, 172),
    ("H = 21", 36.4, 32, 363),
]

# results/undertow.md: what each row needs, at depths j <= 4
ROWS = [
    # n, classical sweep ceiling (n+2)//2, Undertow ceiling as measured
    (37, 19, 18),
    (38, 20, 18),
    (39, 20, 19),
    (40, 21, 19),
    (41, 21, 19),
]

# Row 40's provenance under the rule-independent construction
# (experiments/undertow_ri.py, hmax=18, jmax=4)
RI_MOTLEY_MAX = 18
RI_GAP = [19]
RI_TOWER_MIN = 20
ROW = 40


def bar(v, vmax, width=40, ch="#"):
    n = max(1, round(width * v / vmax))
    return ch * n


def main():
    out = []
    w = out.append

    w("# What Undertow changed — the picture")
    w("")
    w("Generated by `scripts/undertow_picture.py` from banked numbers only.")
    w("Re-run it rather than editing it.")
    w("")

    # ---------------------------------------------------------------- 1
    w("## 1. The heights it removes are the expensive ones")
    w("")
    w("The a(40) run, by phase (`results/ns_a40/PROVENANCE.md`,")
    w("`results/ns_a40/rundir_size.log`). Bars are core-hours; the disk column")
    w("is the run-dir peak reached during that phase.")
    w("")
    w("```")
    ch = [(nm, h * c, d) for nm, h, c, d in PHASES]
    mx = max(v for _, v, _ in ch)
    w("            core-hours                              cpu-h    wall      disk")
    for (nm, h, c, d), (_, ch_v, _) in zip(PHASES, ch):
        keep = "  KEPT" if nm == "H <= 19" else "  REMOVED"
        w(f"  {nm:<8} {bar(ch_v, mx):<40} {ch_v:5.0f}  {h:5.1f}h/{c}c  {d:4d} GB{keep}")
    w("```")
    w("")
    tot_ch = sum(v for _, v, _ in ch)
    kept = ch[0][1]
    w(f"The two removed heights are **{100*(tot_ch-kept)/tot_ch:.0f}% of the core-hours**")
    w(f"and take the disk peak from {PHASES[2][3]} GB to {PHASES[0][3]} GB. The")
    w("`reach-scaling-and-resourcing` memory calls the engine disk/spill-bound")
    w("and puts the home boxes' ceiling there — so this is the axis that was")
    w("actually binding.")
    w("")

    # ---------------------------------------------------------------- 2
    w("## 2. Where each row's cells come from")
    w("")
    w("One line per row, one character per height:")
    w("")
    w("    #   swept, and still swept under Undertow")
    w("    X   swept ONLY because the classical rule needed it -- what Undertow")
    w("        deletes, and always the tallest, most expensive heights")
    w("    .   supplied by the diagonal tower")
    w("")
    w("```")
    w("        H=1" + " " * 21 + "H=n")
    for n, old, new in ROWS:
        line = "".join("#" if H <= new else ("X" if H <= old else ".")
                       for H in range(1, n + 1))
        w(f"  a({n})  {line}   sweep H<={new}, was H<={old}")
    w("```")
    w("")
    w("Two heights come off rows 40 and 41, one off rows 39 and 37: the classical")
    w("ceiling `(n+2)/2` and the Undertow ceiling `(n-3)/2` each move by one for")
    w("every two of `n`, so which rows gain two is a parity question.")
    w("")
    w("Every `X` in that figure is a height whose cost is roughly 3x the one")
    w("below it. The two `X`s on row 40 are the 461 and 1165 core-hour bars of")
    w("section 1.")
    w("")

    # ---------------------------------------------------------------- 3
    w("## 3. Row 40, by who vouches for each cell")
    w("")
    w("`experiments/undertow_ri.py`, using no incumbent file: Motley's own rows")
    w("(a different connectivity rule) below, the tower above, each row excluded")
    w("from its own pinning set.")
    w("")
    w("```")
    seg = []
    for H in range(1, ROW + 1):
        if H <= RI_MOTLEY_MAX:
            seg.append("M")
        elif H in RI_GAP:
            seg.append("?")
        else:
            seg.append("T")
    w("  row 40   " + "".join(seg))
    w("           " + " " * (RI_GAP[0] - 1) + "^")
    w(f"           {' ' * (RI_GAP[0] - 1)}the one cell: T(40,{RI_GAP[0]})")
    w("")
    w(f"  M = Motley, H <= {RI_MOTLEY_MAX}            {RI_MOTLEY_MAX} cells")
    w(f"  T = tower, H >= {RI_TOWER_MIN}              {ROW - RI_TOWER_MIN + 1} cells,"
      f" all {ROW - RI_TOWER_MIN + 1} agreeing with the incumbent")
    w(f"  ? = neither                     {len(RI_GAP)} cell")
    w("```")
    w("")
    w("Before tonight the same construction reached `a(n)` for **n <= 35**")
    w("(HANDOFF, Confetti). It now reaches **n <= 39** complete, with row 40")
    w("short by that single cell.")
    w("")

    # ---------------------------------------------------------------- 4
    w("## 4. The rule, in one line")
    w("")
    w("```")
    w("  classical:   sweep every height up to (n+2)/2,  tower above")
    w("  Undertow:    sweep every height up to (n-3)/2,  tower above")
    w("")
    w("               because a level's two anchors may sit BELOW its onset,")
    w("               where the cells are shorter, instead of above it, where")
    w("               they are the tallest cells on the diagonal.")
    w("```")
    w("")
    w("A height is worth about 3x in compute, so two heights is about 9x — and,")
    w("as §1 shows, it is the disk that moves furthest.")

    print("\n".join(out))


if __name__ == "__main__":
    main()
